module.exports = {
  "cz-dark-color": "#222222",
  "cz-normal-color": "#666666",
  "btn-height-lg": "36px",
  "input-color":"#222222",
  "primary-color": "#5B9BF2",
  "font-size-base": "13px",
  "input-height-base": "30px",
  "input-padding-horizontal": "6px",
  "control-padding-horizontal": '6px',
  "border-radius-base": "2px",
  "border-color-base": '#D3D9E6',
  'table-header-bg': '#F4F5F9',
  'table-row-hover-bg': '#EEF8FF',
  'table-padding-vertical': '7px',
  'table-padding-horizontal': '6px',
  'btn-danger-color': '#FF6868',
  'font-family': '"Microsoft YaHei", "Monospaced Number", Helvetica, Arial, "Microsoft YaHei", "Chinese Quote", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "PingFang SC", "Hiragino Sans GB", "Helvetica Neue", sans-serif',
  'font-family-no-number': 'Helvetica, Arial, "Microsoft YaHei", "Chinese Quote", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "PingFang SC", "Hiragino Sans GB", "Helvetica Neue", sans-serif',
  'cz-normal-boxshadow': '0 2px 8px 0 rgba(112, 122, 137, 0.1)',
  'cz-danger-red': '#FF7979',
  'red': '#FF7979',
  'error-color': '#FF6868',
  'tooltip-bg': 'rgba(55, 76, 118, 0.8)',
  'tooltip-color': '#fff',
  "cz-light-color": "#999999",
  "popover-arrow-width": "8px",
  "cz-green": "#009335"
}
